# =============================================================================
# SUPPLY CHAIN DATA ANALYSIS
# Author   : Vikash Kumawat
# Date     : 26-03-2026
# Tools    : Python | Pandas | NumPy | Plotly | VS Code
# Dataset  : supply_chain.csv
# =============================================================================


# -----------------------------------------------------------------------------
# SECTION 1 — IMPORT LIBRARIES
# -----------------------------------------------------------------------------
# numpy (np)     → Mathematical operations on arrays.
# pandas (pd)    → Data manipulation and analysis via DataFrames.
# plotly.express → High-level interactive charts (scatter, pie, line, bar).
# plotly.io      → Controls chart settings like default theme.
# graph_objects  → Lower-level Plotly for manual chart customization.
# -----------------------------------------------------------------------------

import numpy as np
import pandas as pd
import plotly.express as px
import plotly.io as pio
import plotly.graph_objects as go

pio.templates.default = "plotly_white"


# -----------------------------------------------------------------------------
# SECTION 2 — LOAD DATASET
# -----------------------------------------------------------------------------
# pd.read_csv() → Reads CSV and converts it into a Pandas DataFrame.
# df.head()     → Shows first 5 rows to verify data loaded correctly.
# Dataset has 24 columns: SKU, Price, Revenue, Stock levels, Lead times,
# Shipping carriers, Manufacturing costs, Defect rates, etc.
# -----------------------------------------------------------------------------

df = pd.read_csv("/Users/apple/Downloads/supply_chain - supply_chain.csv")
print(df.head())


# -----------------------------------------------------------------------------
# SECTION 3 — PRICE vs REVENUE BY PRODUCT TYPE (SCATTER PLOT)
# -----------------------------------------------------------------------------
# Scatter plot  → Each dot = one SKU. Shows relationship between Price & Revenue.
# color         → Different color per product type for easy comparison.
# hover_data    → Shows extra info on hover.
# trendline='ols' → Regression line showing overall trend (+ or - correlation).
# INSIGHT: Skincare shows positive trend (higher price = more revenue).
# -----------------------------------------------------------------------------

fig = px.scatter(df, x='Price', y='Revenue generated',
                 color='Product type',
                 hover_data=['Number of products sold'],
                 trendline='ols',
                 title='Price vs Revenue Generated by Product Type')
fig.show()


# -----------------------------------------------------------------------------
# SECTION 4 — SALES DISTRIBUTION BY PRODUCT TYPE (DONUT CHART)
# -----------------------------------------------------------------------------
# groupby().sum() → Total units sold per product type.
# hole=0.5        → Donut-style chart.
# INSIGHT: Skincare 45% | Haircare 29.5% | Cosmetics 25.5%.
# -----------------------------------------------------------------------------

sales_data = df.groupby("Product type")["Number of products sold"].sum().reset_index()
print(sales_data)

pie_chart = px.pie(sales_data, values="Number of products sold", names="Product type",
                   title="Sales by Product Type",
                   hole=0.5,
                   color_discrete_sequence=px.colors.qualitative.Pastel)
pie_chart.update_traces(textposition='inside', textinfo='percent+label')
pie_chart.show()


# -----------------------------------------------------------------------------
# SECTION 5 — TOTAL REVENUE BY SHIPPING CARRIER (BAR CHART)
# -----------------------------------------------------------------------------
# go.Figure()    → Creates blank Plotly canvas.
# go.Bar()       → Adds bar chart layer to the figure.
# update_layout()→ Sets title and axis labels.
# INSIGHT: Carrier B generates highest revenue (~250k) vs A (~140k), C (~180k).
# -----------------------------------------------------------------------------

total_revenue = df.groupby('Shipping carriers')['Revenue generated'].sum().reset_index()

fig = go.Figure()
fig.add_trace(go.Bar(x=total_revenue['Shipping carriers'],
                     y=total_revenue['Revenue generated']))
fig.update_layout(title='Total Revenue by Shipping Carrier',
                  xaxis_title='Shipping Carrier',
                  yaxis_title='Revenue Generated')
fig.show()


# -----------------------------------------------------------------------------
# SECTION 6 — DEFECT RATES BY PRODUCT TYPE (DONUT CHART)
# -----------------------------------------------------------------------------
# Defect Rate → % of products that fail quality inspection.
# High defect = more returns, waste, and customer dissatisfaction.
# INSIGHT: Skincare 41% | Haircare 37.1% | Cosmetics 21.9%.
# Skincare leads in both sales AND defects — quality control needed urgently.
# -----------------------------------------------------------------------------

defect_rates = df.groupby('Product type')['Defect rates'].sum().reset_index()

pie_chart = px.pie(defect_rates, values='Defect rates', names='Product type',
                   title='Defect Rates by Product Type',
                   hole=0.5,
                   color_discrete_sequence=px.colors.qualitative.Pastel)
pie_chart.update_traces(textposition='inside', textinfo='percent+label')
pie_chart.show()


# -----------------------------------------------------------------------------
# SECTION 7 — AVERAGE LEAD TIME & MANUFACTURING COST BY PRODUCT TYPE
# -----------------------------------------------------------------------------
# Lead Time         → Days from order placement to product delivery.
# Manufacturing Cost→ Total cost to produce one unit.
# groupby().mean()  → Average value per product type.
# pd.merge()        → Combines both results into one table.
# -----------------------------------------------------------------------------

avg_lead_time = df.groupby('Product type')['Lead time'].mean().reset_index()
avg_manufacturing_costs = df.groupby('Product type')['Manufacturing costs'].mean().reset_index()

result = pd.merge(avg_lead_time, avg_manufacturing_costs, on='Product type')
result.rename(columns={'Lead time': 'Average Lead Time',
                       'Manufacturing costs': 'Average Manufacturing Costs'}, inplace=True)
print(result)


# -----------------------------------------------------------------------------
# SECTION 8 — REVENUE GENERATED BY SKU (LINE CHART)
# -----------------------------------------------------------------------------
# SKU (Stock Keeping Unit) → Unique code for each product variant.
# Line chart → Shows revenue trend across all SKUs.
# Peaks = high-revenue products | Troughs = underperformers.
# -----------------------------------------------------------------------------

revenue_chart = px.line(df, x='SKU', y='Revenue generated',
                        title='Revenue Generated by SKU')
revenue_chart.show()


# -----------------------------------------------------------------------------
# SECTION 9 — STOCK LEVELS BY SKU (LINE CHART)
# -----------------------------------------------------------------------------
# Stock Levels → Units currently available in inventory.
# Too high → Storage cost rises | Too low → Risk of stockouts.
# -----------------------------------------------------------------------------

stock_chart = px.line(df, x='SKU', y='Stock levels',
                      title='Stock Level by SKU')
stock_chart.show()


# -----------------------------------------------------------------------------
# SECTION 10 — ORDER QUANTITIES BY SKU (BAR CHART)
# -----------------------------------------------------------------------------
# Order Quantity → Units ordered/replenished per SKU.
# High order + low stock = supply shortage risk.
# -----------------------------------------------------------------------------

order_chart = px.bar(df, x='SKU', y='Order quantities',
                     title='Order Quantities by SKU')
order_chart.show()


# -----------------------------------------------------------------------------
# SECTION 11 — SHIPPING COSTS BY CARRIER (BAR CHART)
# -----------------------------------------------------------------------------
# Compares shipping cost across Carrier A, B, C.
# Helps evaluate cost vs. revenue to find the most efficient carrier.
# -----------------------------------------------------------------------------

shipping_cost_chart = px.bar(df, x='Shipping carriers', y='Shipping costs',
                             title='Shipping Costs by Carrier')
shipping_cost_chart.show()


# -----------------------------------------------------------------------------
# SECTION 12 — AVERAGE COST BY TRANSPORTATION MODE (DONUT CHART)
# -----------------------------------------------------------------------------
# Transportation Modes → Road, Air, Sea, Rail.
# groupby().mean()     → Average logistics cost per mode.
# -----------------------------------------------------------------------------

Tc = df.groupby('Transportation modes')['Costs'].mean().reset_index()
print(Tc)

transport_pie = px.pie(Tc, values='Costs', names='Transportation modes',
                       title='Average Cost by Transportation Mode',
                       hole=0.5,
                       color_discrete_sequence=px.colors.qualitative.Pastel)
transport_pie.update_traces(textposition='inside', textinfo='percent+label')
transport_pie.show()


# =============================================================================
# KEY INSIGHTS SUMMARY
# =============================================================================
# 1. Price vs Revenue   → Skincare: higher price = higher revenue (positive trend).
# 2. Sales Share        → Skincare dominates at 45% of total units sold.
# 3. Shipping Carriers  → Carrier B generates the most revenue (~250k).
# 4. Defect Rates       → Skincare has highest defects (41%) — needs QC fix.
# =============================================================================
